<?php
/* ****************************************************************************
GenMaterial 
@author     XXTH (Ohmtal Games)
@created    2023-03-26 

XXTH 2023-11-01 added replace of filename character from "-" to "__" 

                    WARNINGS
                    ========
* Textures must follow a nameing style (case insensitive):  
     _NRM or _NORMAL or _NM for normals
     _SPEC for spec  
     _DETAIL or _dl for details  


* Detail are used for TerrainMaterials only at the moment!

**************************************************************************** */
class GenMaterials
{
    protected
      $fileList = array()
      , $nrmHash  = array() //as hash table [baseNameDiffuse]=nrm file baseName
      , $specHash  = array() //as hash table [baseNameDiffuse]=spec file baseName
      , $detailHash  = array() //as hash table [baseNameDiffuse]=detail file baseName
      , $diffuseList  = array() //as normal array
      
      ,$materialsString = ""
      , $ext    = array("png","dds","jpg","jpeg")
      , $nrm    = array("_nm","_nrm","_normal")
      , $spec   = array("_spec")
      , $detail = array("_detail", "_dl")
      ;
    public
          $castDynamicShadows = false
        , $materialTag = "AutoGenerated"
        , $genTerrainMaterial = false
        ;
    
    public function __construct($path = "./")
    {
        $this->fileList = scandir($path);
    }
    //-------------------------------------------------------------------------
    public function getCount() 
    {
        return $this->getCount();
    }
    //-------------------------------------------------------------------------
    protected function getFileExt($filename)
    {
        $arr = explode('.', $filename);
        $cnt = count($arr);
        if ($cnt>1)
        {
            return strtolower($arr[$cnt-1]);
        }
        return "";
    }
    //-------------------------------------------------------------------------
    protected function isValidExt($ext)
    {
        $ext = strtoLower($ext);
        return (in_array($ext, $this->ext));
    }
    //-------------------------------------------------------------------------
    
    protected function isDetail($filename)
    {
        $filenameLower = strtolower($filename);
        foreach ($this->ext as $ext)
        {
            foreach ($this->detail as $detail)
            {
                $search = $detail.".".$ext;
                
                if (strpos($filenameLower,$search) > 0)
                {
                    $baseName = baseName($filename, ".".$ext);
                    $baseNameDiffuse = preg_replace("/".$search."/i","", $filename);
echo("//***** GOT DETAIL (ext:".$ext." search:$search) : ".$baseName. " FOR DIFFUSE: ".$baseNameDiffuse."\n" );
                    $this->detailHash[$baseNameDiffuse] = $baseName;
                    
                    return true;
                }
            }
        }
        return false;
    }
    //-------------------------------------------------------------------------
    protected function isSpec($filename)
    {
        $filenameLower = strtolower($filename);
        foreach ($this->ext as $ext)
        {
            foreach ($this->spec as $spec)
            {
                $search = $spec.".".$ext;
                
                if (strpos($filenameLower,$search) > 0)
                {
                    $baseName = baseName($filename, ".".$ext);
                    $baseNameDiffuse = preg_replace("/".$search."/i","", $filename);
                    //echo("//***** GOT SPEC (ext:".$ext." search:$search) : ".$baseName. " FOR DIFFUSE: ".$baseNameDiffuse."\n" );
                    $this->specHash[$baseNameDiffuse] = $baseName;
                 
                    return true;
                }
            }
        }
        return false;
    }
    //-------------------------------------------------------------------------    
    protected function isNrm($filename)
    {
        $filenameLower = strtolower($filename);
        foreach ($this->ext as $ext)
        {
            foreach ($this->nrm as $nrm)
            {
                $search = $nrm.".".$ext;
                if (strpos($filenameLower,$search) > 0)
                {
                    $baseName = baseName($filename, ".".$ext);
                    $baseNameDiffuse = preg_replace("/".$search."/i","", $filename);
                    // echo("//***** GOT NRM : ".$baseName. " FOR DIFFUSE: ".$baseNameDiffuse."\n" );                    
                    $this->nrmHash[$baseNameDiffuse] = $baseName;
                                        
                    
                    return true;
                }
            }
        }
        return false;
    }
    
    
    private function guessMatName( $baseName )
    {
        // a number as first character is not allowed
        // so we set the Material_ in front!  
    
        $result =  preg_replace('/\./', '__', "Material_".$baseName);
        $result =  preg_replace('/ /', '__', "Material_".$baseName);
        $result =  preg_replace('/-/', '__', "Material_".$baseName); //2023-11-01
        return $result;
    }
    
    private function getMaterialDef( $baseName )
    {
        $matName = $this->guessMatName($baseName);
        $temp="";
        $temp.="singleton Material(".$matName.")\n";
        $temp.="{\n";
        $temp.="\tmapTo = \"".$baseName."\";\n";
        $temp.="\tdiffuseMap[0] = \"./".$baseName."\";\n";
     
        
        if ( isset($this->nrmHash[$baseName]) && !empty($this->nrmHash[$baseName]) ) {
            $temp.="\tnormalMap[0] = \"./".$this->nrmHash[$baseName]."\";\n";
        }
        if ( isset($this->specHash[$baseName]) && !empty($this->specHash[$baseName]) ) {
            $temp.="\tspecularMap[0] = \"./".$this->specHash[$baseName]."\";\n";
        }
        
        
        
        $temp.="\tmaterialTag0 = \"".$this->materialTag."\";\n";
        if ($this->castDynamicShadows)
        {
            $temp.="\tcastDynamicShadows = \"1\";\n";
        }
        $temp.="};\n";
        
        return $temp;
    }
    
    
    //-------------------------------------------------------------
    //Terrain materials
    //-------------------------------------------------------------
    private function getTerrainMaterialDef( $baseName )
    {
        //first the material dest
        
        $matName = $this->guessMatName($baseName);
        $temp="";
        $temp.="singleton Material(".$matName.")\n";
        $temp.="{\n";
        $temp.="\tmapTo = \"".$baseName."\";\n";
        $temp.="\tfootstepSoundId = FootHardSound;\n";
        $temp.="};\n";
        
        //next the material 
        
        $temp.="new TerrainMaterial()\n";
        $temp.="{\n";
        
        $temp.="\tinternalName = \"".$this->materialTag.$baseName."\";\n";
        $temp.="\tdiffuseMap = \"./".$baseName."\";\n";
        $temp.="\tdiffuseSize = \"256\";\n";
        if ( isset($this->detailHash[$baseName]) && !empty($this->detailHash[$baseName]) ) {
            $temp.="\tdetailMap = \"./".$this->detailHash[$baseName]."\";\n";
        } else {
            $temp.="\tdetailMap = \"./".$baseName."\";\n";
        }
        $temp.="\tdetailSize = \"10\";\n";
        $temp.="\tdetailStrength = \"0.8\";\n";
        $temp.="\tdetailDistance = \"500\";\n";
        
        
        if ( isset($this->nrmHash[$baseName]) && !empty($this->nrmHash[$baseName]) ) {
            $temp.="\tnormalMap = \"./".$this->nrmHash[$baseName]."\";\n";
            $temp.="\tparallaxScale = \"0.03\";\n";
        }
        $temp.="};\n";
        
        
        
        return $temp;
    }
    
    
    //-------------------------------------------------------------------------
    public function execute() 
    {
        $this->nrmHash   = array();
        $this->specHash  = array();
        $this->detailHash = array();
        $this->materialsString = "";
        $this->count = 0;
        
        //loop all files
        foreach ($this->fileList as $filename)
        {
            $ext = $this->getFileExt($filename);
            if ($this->isValidExt($ext))
            {
                
                $baseName = baseName($filename, ".".$ext);
                
                if ($this->isNrm($filename))
                {
                    continue;
                }
                if ($this->isSpec($filename))
                {
                    continue;
                }
                
                $this->diffuseList[]=$baseName;
                
               
                
            }
        }

        //loop DiffuseList
        foreach($this->diffuseList as $diffuseBaseName)
        {
            
            if ($this->genTerrainMaterial)
            {
                $this->materialsString .= $this->getTerrainMaterialDef($diffuseBaseName);
            } else {
                $this->materialsString .= $this->getMaterialDef($diffuseBaseName);
            }
            
        }
        
        $header  = "//-------------------------------------------------------------------------\n";
        $header .= "// Autogenerated by Ohmtals GenMaterials Tool\n";
        $header .= "// Found Diffuse Textures ".count($this->diffuseList)."\n";
        $header .= "// Found Normal Textures ".count($this->nrmHash)."\n";
        $header .= "// Found Spec Textures ".count($this->specHash)."\n";
        $header .= "//-------------------------------------------------------------------------\n";
        
        $this->materialsString = $header.$this->materialsString;
        
        return $this->materialsString;
    } //execute
    
} //class 

?>